# Trabajo final Datux Python - Ejercicio 1_DataFrames y Series

## Importar pandas

In [2]:
import os
import pandas as pd

## Crear una serie

### Serie de los números 10, 20, 10

In [4]:
numeros={'1°': 10, '2°': 20, '3°': 10}
serie1=pd.Series(data=numeros, index=['1°', '2°', '3°'])
serie1

1°    10
2°    20
3°    10
dtype: int64

### Serie con tres objetos "rojo", "verde", "azul"

In [5]:
colores={'color 1': "rojo", 'color 2': "verde", 'color 3': "azul"}
serie2=pd.Series(data=colores, index=['color 1', 'color 2', 'color 3'])
serie2

color 1     rojo
color 2    verde
color 3     azul
dtype: object

## Crear un dataframe

### Dataframe vacío llamado 'df'

In [6]:
import pandas as pd
df=pd.DataFrame()

### Creación de una nueva columna en el dataframe, y asignale la primera serie que se ha creado

In [7]:
import os
import pandas as pd
numeros={'1°': 10, '2°': 20, '3°': 10}
serie1=pd.Series(data=numeros, index=['1°', '2°', '3°'])

df=pd.DataFrame({'Columna 1': serie1})
print(df)

    Columna 1
1°         10
2°         20
3°         10

### Creación de otra columna en el dataframe, y asignar la segunda serie que se ha creado

In [8]:
import os
import pandas as pd

numeros={'1°': 10, '2°': 20, '3°': 10}
serie1=pd.Series(data=numeros, index=['1°', '2°', '3°'])

colores={'color 1': "rojo", 'color 2': "verde", 'color 3': "azul"}
serie2=pd.Series(data=colores, index=['color 1', 'color 2', 'color 3'])

df=pd.DataFrame({'Columna 1': serie1, 'Columna 2': serie2})
print(df)

         Columna 1 Columna 2
1°            10.0       NaN
2°            20.0       NaN
3°            10.0       NaN
color 1        NaN      rojo
color 2        NaN     verde
color 3        NaN      azul

## Leer un DataFrame

### Leer el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'.El archivo está localizado en "data/avengers.csv".

In [2]:
import pandas as pd

df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
print(df)

                                                   URL  \
0        http://marvel.wikia.com/Henry_Pym_(Earth-616)
1    http://marvel.wikia.com/Janet_van_Dyne_(Earth-...
2    http://marvel.wikia.com/Anthony_Stark_(Earth-616)
3    http://marvel.wikia.com/Robert_Bruce_Banner_(E...
4     http://marvel.wikia.com/Thor_Odinson_(Earth-616)
..                                                 ...
168   http://marvel.wikia.com/Eric_Brooks_(Earth-616)#
169  http://marvel.wikia.com/Adam_Brashear_(Earth-6...
170  http://marvel.wikia.com/Victor_Alvarez_(Earth-...
171     http://marvel.wikia.com/Ava_Ayala_(Earth-616)#
172         http://marvel.wikia.com/Kaluu_(Earth-616)#

                          nombre  n_apariciones actual  genero  fecha_inicio  \
0      Henry Jonathan "Hank" Pym           1269    YES    MALE          1963
1                 Janet van Dyne           1165    YES  FEMALE          1963
2    Anthony Edward "Tony" Stark           3068    YES    MALE          1963
3            Robert Bruce Banner           2089    YES    MALE          1963
4                   Thor Odinson           2402    YES    MALE          1963
..                           ...            ...    ...     ...           ...
168                  Eric Brooks            198    YES    MALE          2013
169                Adam Brashear             29    YES    MALE          2014
170               Victor Alvarez             45    YES    MALE          2014
171                    Ava Ayala             49    YES  FEMALE          2014
172                        Kaluu             35    YES    MALE          2015

                                                 Notes
0    Merged with Ultron in Rage of Ultron Vol. 1. A...
1    Dies in Secret Invasion V1:I8. Actually was se...
2    Death: "Later while under the influence of Imm...
3    Dies in Ghosts of the Future arc. However "he ...
4    Dies in Fear Itself brought back because that'...
..                                                 ...
168                                                NaN
169                                                NaN
170                                                NaN
171                                                NaN
172                                                NaN

[173 rows x 7 columns]

## Inspeccionar un DataFrame

### Muestra las primeras 5 filas del DataFrame.

In [3]:
import pandas as pd

df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.head()

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

### Muestra las primeras 10 filas del DataFrame

In [4]:
import pandas as pd
df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.head(10)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
6,http://marvel.wikia.com/Steven_Rogers_(Earth-616),Steven Rogers,3458,YES,MALE,1964,Dies at the end of Civil War. Later comes back.
7,http://marvel.wikia.com/Clint_Barton_(Earth-616),Clinton Francis Barton,1456,YES,MALE,1965,Dies in exploding Kree ship in Averngers Vol. ...
8,http://marvel.wikia.com/Pietro_Maximoff_(Earth...,Pietro Maximoff,769,YES,MALE,1965,Dies in House of M Vol 1 Issue 7. Later comes ...
9,http://marvel.wikia.com/Wanda_Maximoff_(Earth-...,Wanda Maximoff,1214,YES,FEMALE,1965,Dies in Uncanny_Avengers_Vol_1_14. Later comes...

### Muestra las últimas 5 filas del DataFrame

In [5]:
import pandas as pd
df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.tail()

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

## Tamaño del DataFrame

### Muestra el tamaño del DataFrame

In [6]:
import pandas as pd
df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.shape

(173, 7)

## Data types en un DataFrame

### Muestra los data types del dataframe

In [7]:
import pandas as pd
df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.dtypes

URL              object
nombre           object
n_apariciones     int64
actual           object
genero           object
fecha_inicio      int64
Notes            object
dtype: object

## Editar el indice (index)

### Cambia el indice a la columna "fecha_inicio".

In [8]:
import pandas as pd
df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.set_index('fecha_inicio')

,URL,nombre,n_apariciones,actual,genero,Notes
fecha_inicio,,,,,,
1963,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,Merged with Ultron in Rage of Ultron Vol. 1. A...
1963,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,Dies in Secret Invasion V1:I8. Actually was se...
1963,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,"Death: ""Later while under the influence of Imm..."
1963,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,"Dies in Ghosts of the Future arc. However ""he ..."
1963,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...
2013,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,NaN
2014,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,NaN
2014,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,NaN
2014,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,NaN
2015,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,NaN

## Ordenar el indice

### Ordena el índice de forma descendente

In [9]:
import pandas as pd
import numpy as np

df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.sort_values(by=['fecha_inicio'], ascending=[False])

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN
157,http://marvel.wikia.com/Sam_Alexander_(Earth-6...,Sam Alexander,78,YES,MALE,2015,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
...,...,...,...,...,...,...,...
123,http://marvel.wikia.com/Emery_Schaub_(Earth-616)#,Emery Schaub,26,YES,MALE,1900,NaN
122,http://marvel.wikia.com/James_Santini_(Earth-6...,James Santini,40,YES,MALE,1900,NaN
75,http://marvel.wikia.com/Elvin_Haliday_(Earth-6...,Elvin Haliday,158,NO,MALE,1900,NaN
76,http://marvel.wikia.com/William_Baker_(Earth-6...,William Baker,355,NO,MALE,1900,Died in Identity_Disc_Vol_1_1. Later was revea...
128,http://marvel.wikia.com/Julie_Power_(Earth-616)#,Julie Power,153,YES,FEMALE,1900,NaN

## Resetear el indice

### Resetea el indice

In [10]:
import pandas as pd
import numpy as np

df=pd.read_csv('C:/Users/moseb/Documents/Datux/Python/TrabajoFinal_Datux_Python/FinalPython/src/pandas/avengers.csv', sep=',')
df.sort_values(by=['fecha_inicio'], ascending=[False])
df.reset_index()

,index,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...,...
168,168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN